### ISSUE TITLE
lower versions

### ISSUE THREAD

**Issue by zwkxgod** [Noryea/motionblur-fabric#13]
can u do motion blur on lower versions like 1.16.5? Really a lot of people need on versions like 1.16.5/1.12.2/1.8.9

**Comment by slimakiswinka** [comment]
Duplicate of #3 really

**Comment by Noryea** [comment]
For people looking for 1.8/1.12 version: There is already a motion blur mod for old version running on Forge, see [here](https://modrinth.com/mod/polyblur).
