### ISSUE TITLE
im using sodium and im using satin api. are there any settings or mods that make the motionblur not work?

### ISSUE THREAD

**Issue by Djdizzyflo1** [Noryea/motionblur-fabric#14]
.

**Comment by WalksygyATT** [comment]
same dude idk how this got no replys

**Comment by WalksygyATT** [comment]
@Noryea

**Comment by Noryea** [comment]
send command "/motionblur 0" in chat

**Comment by Djdizzyflo1** [comment]
> send command "/motionblur 0" in chat

it doesn't work, I'm using it on lunar but I know that its usable on lunar

**Comment by Djdizzyflo1** [comment]
also im using a mac. Do macs not render the motion blur?

**Comment by WalksygyATT** [comment]
im pretty sure they do nearly every client with motionblur ive used has rended motionblur flawlessly

**Comment by WalksygyATT** [comment]
@Noryea many reports about like not working on macos maybe upgrade support for different cpus or gpus

**Comment by Noryea** [comment]
> > send command "/motionblur 0" in chat
> 
> it doesn't work, I'm using it on lunar but I know that its usable on lunar

Lunar has its own Motionblur mod, so I recommend not to use my mod on Lunar client

**Comment by Noryea** [comment]
> @Noryea many reports about like not working on macos maybe upgrade support for different cpus or gpus

I don't have a Mac. it's hard for me to find out why my simple mod malfunctions on other operating systems (excluding windows) and that I am not motivated to support Mac OS. sorry for that👉👈

**Comment by WalksygyATT** [comment]
actually without lunar anyways it doesnt work i have inspected the mod in every possible but yet i still cant make it work i set my motionblur to highest but it wont work

**Comment by slimakiswinka** [comment]
If I recall correctly, Apple deprecated OpenGL with M1 and Big Sur, resulting in a lack of proper driver implementation for GLSL and OpenGL. This mod's use of satin to implement a shader doesn't work on MacOS due to these issues.

**Comment by WalksygyATT** [comment]
which mod to use also im on a macos 1l0.13.6 a older version

**Comment by Noryea** [comment]
> which mod to use also im on a macos 1l0.13.6 a older version

Hey, there is a newer version I 've not published yet in [this page](https://github.com/Noryea/motionblur-fabric/actions/runs/8845748833). Could you download "motionblur-jar" and try it with ≥60% motionblur strength to see if it works on ur Mac?

Note that this version is for 1.17(.1)

**Comment by Noryea** [comment]
> 
> Could you download "motionblur-jar" and try it

put the file in "motionblur-jar" whose name is without any suffix like "dev" in your fabric mods directory.
