### ISSUE TITLE
Installed this mod just to test, I go to remove the mod and now MC wont start without it... ???

### ISSUE THREAD

**Issue by rikosama** [Noryea/motionblur-fabric#2]
So im just making a mod pack and have a few different mods, motion blur being one of them that I just wanted to test out. I like it, but I believe its causing some crashing but I cant be to sure being im not that good at reading crash logs and half the time im not even getting one. I just have a feeling this mod is possibly causing that so I go to take the mod out of the mod folder and try to start the game back up and now it wont open. I put the mod back and its working again. Why. Why had my MC fallen in love with this mod, attachment issues? All jokes aside, any help will be appreciated, I know theres almost no info to go off of but like I said, I simply suspect this mod, but now my MC cant run without it. weird. Maybe others have this weird little issue?

**Comment by Noryea** [comment]
I guess your modpack doesn't contain Midnight Lib, which is built

**Comment by Noryea** [comment]
I guess that your modpack doesn't contain Midnight Lib(or Satin API), which is integrated in Motionblur mod

**Comment by rikosama** [comment]
i see, i thought maybe i had the api without the mod and that's what was making it not start but no, never downloaded an app to go with it, still doesn't make sense how the modpack was fine before i added the mod, i test it, remove it and now it wont work without it? weird. maybe i'm missing something and just need to triple check.
