### ISSUE TITLE
Incompatible with resolution control +

### ISSUE THREAD

**Issue by sootysplash** [Noryea/motionblur-fabric#9]
Hangs indefinitely on joining world (with cpu usage stuck on 0%) there are no errors in the latest.log

**Comment by slimakiswinka** [comment]
I checked it on Quilt and Resolution Control + and Motionblur both worked perfectly.
I can't replicate this issue, so please tell me what hardware you have.

**Comment by sootysplash** [comment]
Turns out it's not incompatible with resolution control+, but with res ctrl+ and a third mod in my folder, will test a bit more

**Comment by sootysplash** [comment]
Was able to replicate with res ctrl+, motionblur and sodium (on 1.20.1, fabric), @slimakiswinka mind testing on your own hardware?

**Comment by slimakiswinka** [comment]
Well for me it works:
-Quilt with QFAPI, Iris, Indium, Sodium, Res Ctrl+, Motionblur, Satin API, ModMenu, ViaFabric+ and VoxelMap
I also made a specific test:
-Fabric w/ Sodium, Fabric API, Res Ctrl+, Motionblur, Satin API
 Still can't replicate the bug

**Comment by sootysplash** [comment]
Welp, if it can't be reproduced I guess it's just an issue with my hardware
